package com.gmail.nossr50.neoforge.mixin;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.reflect.Method;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.entity.LivingEntity;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import com.gmail.nossr50.util.McTestRegistries;

class LivingEntityDropFromLootTableAccessorTest {

    @BeforeAll
    static void bootstrapRegistries() {
        McTestRegistries.bootstrap();
    }

    @Test
    void theMixinInterfaceExists() {
        // The mixin creates an interface that should be loadable.
        assertNotNull(LivingEntityDropFromLootTableAccessor.class,
            "Mixin interface class must be loadable");
    }

    @Test
    void theAccessorStaticMethodExists() throws NoSuchMethodException {
        // Verify that the accessor interface's static method exists with the correct signature.
        // This indicates that the mixin was registered and processed.
        final Method method = LivingEntityDropFromLootTableAccessor.class.getDeclaredMethod(
                "invokeDropFromLootTable",
                LivingEntity.class, DamageSource.class, boolean.class);
        assertNotNull(method, "Static invokeDropFromLootTable method must exist");
    }

    @Test
    void theAccessorInvokerMethodWasGenerated() {
        // Verify that the mixin's @Invoker interface method was generated by checking for
        // any method that looks like it could be the private invoker method.
        final Method[] methods = LivingEntityDropFromLootTableAccessor.class.getDeclaredMethods();
        boolean hasInvoker = false;
        for (final Method m : methods) {
            if (m.getName().contains("invoke")) {
                hasInvoker = true;
                break;
            }
        }
        assertTrue(hasInvoker, "Accessor interface must have an invoker method");
    }
}
